# Generated by Django 3.1.7 on 2021-04-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_comments_related_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
