# Generated by Django 3.1.7 on 2021-04-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_category_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
