# Generated by Django 3.1.7 on 2021-03-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210311_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name=''),
        ),
        migrations.AddField(
            model_name='article',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('articles', models.ManyToManyField(related_name='categories', to='news.Article')),
            ],
        ),
    ]
