# Generated by Django 3.1.7 on 2021-05-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_sender_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
